name: terraguard_app
description: TerraGuard - Offline-first AI landslide early warning and field reporting application.
publish_to: 'none'
version: 3.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  provider: ^6.1.1
  lucide_icons: ^0.257.0
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  connectivity_plus: ^6.1.0
  geolocator: ^13.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.0
  path: ^1.9.0
  sqflite: ^2.3.3+1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
